package inb370.asgn1;

/**
 * This class represents any exceptions generated by the Hiring Game. If you
 * discover an invalid condition during the game you should throw a new instance
 * of this class.
 * 
 * @author INB370
 * @version 1.0
 */
public class HiringException extends Exception {

	/**
	 * Creates a new instance of HiringException.
	 * 
	 * @param msg An informative message about the problem found.
	 */
	public HiringException(String msg) {
		super("Hiring Exception: " + msg);
	}

}
